version: "3"

services:

  service:
    image: ${DOCKER_IMAGE}
    entrypoint: nc
    command: >
      -lk -p 8080 -v -e /bin/sh -c '
        sleep 0.1;
        echo "HTTP/1.1 200 OK";
        echo "Content-Type: text/plain; charset=$${CHARSET}";
        echo "Content-Length: $$(date | wc -m)";
        echo ;
        date
      '

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - service
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - ENTRYPOINT_DEBUG=true
      - WAIT_FOR_URL=http://service:8080
      - WAIT_FOR_TIMEOUT=10
    working_dir: ${TEST_DIR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TEST_DIR}:${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - service
    command:
      - "true"
    environment:
      - ENTRYPOINT_DEBUG=true
      - WAIT_FOR_URL=http://service:8080
      - WAIT_FOR_TIMEOUT=10
